name: Format and Lint Python Code

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: ${{ github.head_ref }}
    
    - name: Import bot's GPG key for signing commits
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_KEY_PASPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e . 
        pip install -e .[dev]
        pip install black isort flake8

    - name: Run Black
      run: black .

    - name: Run isort
      run: isort .

    - name: Commit Changes with GPG Signature
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/RedLion8399/Dino.git
        git add .
        git commit -m "Format code with black and isort" || echo "No changes to commit"
        git fetch origin
        git rebase origin/${{ github.head_ref }}
        git push origin HEAD:${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}

    # Unused for now activated until the resst works
    # - name: Run Flake8 Linting
    #   run: |
    #     flake8 . --count --select=E,F --show-source --statistics
    #     flake8 . --count --exit-zero --max-line-length=88 --statistics
